parent=base
import=common/keycloak

styles=css/login.css

# ----- Keycloak CSS class mappings -----
kcHtmlClass=
kcBodyClass=kc-body
kcFormGroupClass=kc-form-group
kcLabelClass=kc-label
kcInputClass=kc-input
kcInputGroup=kc-input-group
kcInputErrorMessageClass=kc-input-error
kcButtonClass=kc-btn
kcButtonPrimaryClass=kc-btn--primary
kcButtonDefaultClass=kc-btn--default
kcButtonLargeClass=kc-btn--large
kcButtonBlockClass=kc-btn--block
kcFormPasswordVisibilityButtonClass=kc-password-toggle
kcFormPasswordVisibilityIconShow=fa fa-eye
kcFormPasswordVisibilityIconHide=fa fa-eye-slash
